name: Run InstaWP script

on:
  push:
    branches:
      - development

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Compile scripts
        run: pnpm exec tsc -p scripts/tsconfig.json

      - name: Run script
        run: node scripts/dist/instawp.js
        env:
          INSTAWP_API_KEY: ${{secrets.INSTAWP_API_KEY}}
